# Copyright 2016 Google Inc. All rights reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Example config file for running under Google App Engine.

# To deploy this module to your app, run the following command:
#   gcloud preview app deploy config/app.yaml

runtime: custom
vm: true

# If you want to lock down access to your review lists to members of
# your project, then uncomment the following 4 lines:
#handlers:
#- url: /.*
#  script: main.application
#  login: admin
